### ISSUE TITLE
[CONCERN] Mythic metals does not have lutetium ore

### ISSUE THREAD

**Issue by FewerFlaws** [DaFuqs/StarrySky#8]
The mythic metals integration code refers to lutetium ore, which does not exist in the current version of mythic metals.  I didn't see any error handling code in a cursory glance so I thought I should point this out for review.

https://github.com/DaFuqs/StarrySky/blob/master/src/main/java/de/dafuqs/starrysky/spheroid/lists/SpheroidListMythicMetals.java#L31

**Comment by DaFuqs** [comment]
You're right. [Lutetium seemed to exist in 0.9.7](https://github.com/Noaaan/MythicMetals/blob/2cfef6d078bc3a896849f1030fc21e3b4057a602/PATCHNOTES.md#097). But it seems like it has been removed since then.

Comparing [Starrys mythic metals integration](https://github.com/DaFuqs/StarrySky/blob/master/src/main/java/de/dafuqs/starrysky/spheroid/lists/SpheroidListMythicMetals.java) and the [mythic metal ores](https://github.com/Noaaan/MythicMetals/blob/MASTER/src/main/java/nourl/mythicmetals/ores/MythicMetalsOres.java) lutetium is the only ore missing. 

I'll remove that one.

Trying to generate a lutetium ore spheroid will trigger an [error in the logs](https://github.com/DaFuqs/StarrySky/blob/master/src/main/java/de/dafuqs/starrysky/spheroid/types/CoreSpheroidType.java#L31) and generate air instead currently.

Incidentally I've added additional block checks at startup while wolking on the Better Nether and BetterEnd support. I'll link that commit here, once it's pushed.

**Comment by DaFuqs** [comment]
Better block logging was implemented in beb1e527f2e4815b1b99fc2d3ad90454127c187c

**Comment by Noaaan** [comment]
As a future warning: I might remove a few more ores before v1.0. I will let you know before I do it

**Comment by DaFuqs** [comment]
Perfect, thank you, @Noaaan ! :)
